---
- name: Make sure the deconz container is created and running
  docker_container:
    name: "deconz"
    image: "deconzcommunity/deconz"
    pull: yes
    state: 'started'
    network_mode: host
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0:rwm"
    env:
      "DECONZ_DEVICE": "/dev/ttyACM0"
      "DECONZ_WEB_PORT": "8085"
      "DECONZ_VNC_PORT": "5900"
      "DECONZ_NOVNC_PORT": "6080"
      "DECONZ_VNC_MODE": "1"
      "DECONZ_WS_PORT": "4043"
      "DEBUG_INFO": "1"
      "DEBUG_APS": "0"
      "DEBUG_ZCL": "0"
      "DEBUG_ZDP": "0"
      "DEBUG_OTAU": "0"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_home }}/deCONZ:/opt/deCONZ"
    restart_policy: unless-stopped