---
- name: Make sure the Wireguard container is created and running
  docker_container:
    name: "wireguard"
    image: "ghcr.io/linuxserver/wireguard"
    pull: yes
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
      - sys_module
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ ansible_nas_timezone }}"
      "SERVERURL": "{{ pub_domain }}"
      "PEERS": "{{ wireguard_peers }}"
      "PEERDNS": "1.1.1.1, 8.8.8.8"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_home }}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped